name: CopernicusDownloader
channels:
  - conda-forge
  - defaults
dependencies:
  - openssl
  - pip
  - python=3.12
  - pip:
      - jinja2==3.1.3
      - markupsafe==2.1.4
      - pandas==2.2.0
      - pyarrow==15.0.0
      - pytz==2023.4
      - tabulate==0.9.0
      - tzdata==2023.4